version: '3.9'

services:
  db:
    container_name: 'local-mysql'
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - 'mysql-data:/var/lib/mysql'
  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '80:80'
    environment:
      PHP_INI_UPLOAD_MAX_FILESIZE: 64M
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', false);
        define('FS_METHOD', 'direct');
        define('WP_AUTO_UPDATE_CORE', true);
        define('WP_SITEURL', 'http://localhost');
        define('WP_HOME', 'http://localhost');
    volumes:
      - './wordpress:/var/www/html'
      - './plugins:/var/www/html/wp-content/plugins'
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  adminer:
    container_name: 'local-adminer'
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USERNAME: ${MYSQL_USER}
      ADMINER_DEFAULT_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql-data:
    driver: local